/**
 * Legal pages — verbatim from the prototype. Counsel must review before launch
 * (Terms, Refund & Cancellation, Privacy). "All sales final" is load-bearing:
 * the consent record + itemised scope + delivery record are the dispute evidence.
 */
export interface LegalSection { t: string; lines: string[] }
export interface LegalPage {
  slug: string; // route under /
  nav: string;
  kicker: string;
  title: string;
  updated: string;
  intro: string;
  sections: LegalSection[];
}

const UPDATED = "Last updated August 28, 2026";

export const LEGAL: Record<"policies" | "terms" | "refund-policy" | "privacy", LegalPage> = {
  policies: {
    slug: "policies", nav: "Policies & Procedures", kicker: "Policies & procedures",
    title: "How we work, in writing", updated: UPDATED,
    intro: "The operating terms every engagement runs on. These are the same commitments carried in your proposal and contract.",
    sections: [
      { t: "Scope and pricing", lines: ["Scope and pricing are agreed in writing before work begins.", "Anything beyond the agreed scope is quoted before it is done.", "Fixed-rate services — those shown with a set price on Book & Pay — are charged at the published amount for the stated scope.", "Starting-price services — shown as “from,” “starting at,” “custom,” or “quote required” — vary with scope and are quoted in writing before work begins.", "Hard costs — printing, licensing, hosting, venue, catering, paid ads, ISBN and print runs — are billed at cost, meaning the actual amount with no markup."] },
      { t: "Plans and terms", lines: ["Plans run a standard 12-month term.", "Plan fees are billed monthly for the agreed term. You can also pay the year up front and save one month.", "A five business-day grace period applies to monthly fees.", "Standalone projects are paid in full at booking, or as set out in your written quote.", "Renewal happens at the end of the term. Tiers can move up or down at renewal."] },
      { t: "Payment methods", lines: ["We accept various forms of electronic payment through the Stripe secure payment system.", "Payments made on this site cover the amount shown at booking. Plan fees and scoped work are invoiced and paid through a secure payment link.", "Plan fees are billed monthly, or the year can be paid up front."] },
      { t: "Allotments and overage", lines: ["Each plan tier sets your volume across every service line, on the cadence shown in the plan — monthly for most services, and quarterly or once per contract term for certain specialty lines. Some work is project-based and scheduled by capacity, and larger production projects may span more than one period.", "Submittal packages beyond your allotment are billed at a flat $450 per week, covering any number of additional packages that week.", "Additional virtual assistant hours are $55 Foundation, $50 Momentum, $40 Enterprise.", "Rush turnaround is a $550 surcharge added on top of a package price and is never included in any plan.", "Unused allotment does not roll over. Unused capacity is reviewed at your tier cadence.", "Virtual-assistant hours have their own rule: they are scheduled and used day by day, and unused hours within a day do not carry to the next day."] },
      { t: "Delivery and revisions", lines: ["Every deliverable passes a pre-delivery review before it reaches you.", "One revision round is included on standard deliverables. Further revisions are quoted and billed separately.", "Service-specific revision terms — stated on a service page, quote, package, or written agreement — supersede this general allowance where they differ (for example, design deliverables that include two rounds).", "Turnaround is standard at Foundation, priority in queue at Momentum, and priority on everything at Enterprise.", "Work is delivered on your brand and verified for accuracy before release."] },
      { t: "Confidentiality and credentials", lines: ["Your information, credentials and materials are protected and never shared without permission.", "Logins are collected securely through a password manager during week-one onboarding and are never kept in plain text.", "If you offboard, all credentials and assets are returned to you."] },
      { t: "Limits of our work", lines: ["We prepare — we do not certify or stamp engineering. Your general contractor or contractor of record reviews and signs.", "Legal wording is flagged to your attorney and never altered by us.", "We are not a substitute for licensed bookkeeping, legal, or tax services.", "On grant work we research, prepare and submit. No award is guaranteed.", "Specialized surveying, legal or agronomy work is referred out as needed."] },
      { t: "Communication", lines: ["Every plan includes a dedicated account lead as your single point of contact.", "Administrative requests are acknowledged the same business day and actioned in agreed priority.", "Reviews run monthly at Foundation, bi-weekly at Momentum, and weekly at Enterprise.", "Risks and blockers are flagged the day they surface, with a recommended path."] },
    ],
  },
  terms: {
    slug: "terms", nav: "Terms of Service", kicker: "Terms of service",
    title: "Terms of Service", updated: UPDATED,
    intro: "These terms exist so both sides know exactly what to expect. In plain terms: we scope and price everything in writing first, we deliver what we agree to, and if something's wrong we would rather fix it than fight about it. The full terms below govern the use of this website and the purchase of services from Hill Country Consultants — by booking, paying, or signing a proposal you accept them.",
    sections: [
      { t: "1 · Agreement and scope", lines: ["Service descriptions on this site are summaries. The written proposal or contract for your engagement governs what is delivered, at what volume, and on what schedule.", "Where this site and a signed proposal differ, the signed proposal controls.", "Anything outside the agreed scope is quoted in writing and approved before it is performed."] },
      { t: "2 · Fees, billing and authorization", lines: ["All prices are in U.S. dollars.", "Plan fees are billed monthly for the agreed term, and can be paid monthly or up front. A five business-day grace period applies.", "Recurring plan billing: by starting a plan you authorize Hill Country Consultants to charge your payment method the agreed fee on a recurring monthly basis until the term ends or you cancel in writing as your contract provides. The amount, the monthly frequency, and the term are stated in your proposal and on the Plans page. Cancelling stops future renewal and does not refund fees already paid for the current term.", "Standalone projects are paid in full at booking, or as set out in your written quote.", "By submitting payment on this site you authorize Hill Country Consultants to charge the payment method you provide for the amount shown at booking, and for any amounts you later approve in writing.", "Charges appear on your statement as Hill Country Consultants.", "Our refund and dispute policy is presented for your acceptance at checkout before any charge is taken.", "We accept various forms of electronic payment through the Stripe secure payment system, our payment processor. We do not store full card numbers or security codes.", "Work may be paused on accounts past the grace period until the balance is current."] },
      { t: "3 · All sales final", lines: ["All payments are final. We do not issue refunds on plan fees, project payments, class fees, overage, or rush charges. The full policy — including how we make it right if we fail to deliver — is in the Refund & Cancellation Policy.", "This no-refund policy is disclosed and affirmatively accepted at checkout before any charge is taken, and your acceptance is recorded with the transaction.", "We ask that you contact us before disputing a charge; nothing in these terms waives any right the law or your card network provides, and we do not ask you to waive one."] },
      { t: "4 · Your responsibilities", lines: ["Provide accurate information, materials, approvals and access on time, and name one point of contact.", "Hold the rights to any content, logos, data or documents you give us to use.", "Delays caused by missing materials or approvals do not extend an allotment, change a fee, or create a right to a refund."] },
      { t: "5 · Ownership of work", lines: ["On receipt of full payment, you own the final deliverables we produce for you.", "Third-party components are licensed, not transferred: fonts, stock media, plugins and code libraries used in your work remain under their own licenses, and hosting, domains, ISBNs and app-store registrations are held in your own accounts, at cost. Where a book is published through the Redd Ladys Chronicles imprint, rights, royalties and registrations follow your written publishing agreement — you keep your author rights either way.", "We retain our own templates, checklists, internal process documentation, tooling and prompt libraries, including any improvements made while serving you.", "We use your name or work publicly only with your written permission."] },
      { t: "6 · Confidentiality", lines: ["Each party protects the other’s confidential information and does not share it without permission, except where disclosure is required by law.", "Credentials are collected and held through a password manager, and are returned or revoked at offboarding."] },
      { t: "7 · Limits of service", lines: ["We prepare documents and packages. We do not certify or stamp engineering, and your general contractor or contractor of record reviews and signs.", "Legal wording is flagged to your attorney and never altered by us.", "We are not a substitute for licensed bookkeeping, legal, or tax services.", "On grant work we research, prepare and submit. No award is guaranteed."] },
      { t: "8 · Limitation of liability", lines: ["Services are provided as described in your proposal. We do not warrant any specific business outcome, award, approval, ranking or revenue result.", "To the fullest extent permitted by law, our total liability for any claim is limited to the fees you paid for the specific service giving rise to the claim, and for plans, to one month of plan fees.", "Neither party is liable for indirect, incidental, special or consequential damages, or for lost profits."] },
      { t: "9 · Indemnification", lines: ["You agree to indemnify Hill Country Consultants against claims arising from materials or instructions you supply, including claims of infringement, inaccuracy, or unlawful use."] },
      { t: "10 · Term, suspension and termination", lines: ["Plans run the agreed term. Non-renewal or changes take effect at the end of the term unless your contract states otherwise.", "We may suspend or terminate service for non-payment, for breach of these terms, or for abusive conduct toward our team.", "On termination, all amounts already paid remain non-refundable, and work completed to date is delivered."] },
      { t: "11 · Force majeure", lines: ["Neither party is liable for delay caused by events beyond reasonable control, including severe weather, utility or platform outages, or acts of government. Deadlines are extended by the length of the event."] },
      { t: "12 · Governing law and disputes", lines: ["These terms are governed by the laws of the State of Texas and the State of Georgia — the two states in which Hill Country Consultants operates — without regard to conflict-of-law rules.", "Before any formal action, the parties will attempt to resolve the dispute in good faith by direct discussion for thirty days.", "Any action that proceeds is brought in the state or federal courts serving Gregg County, Texas (Longview) or DeKalb County, Georgia (Atlanta), and each party consents to venue in either forum.", "Each party bears its own costs and attorney fees unless a court orders otherwise."] },
      { t: "13 · Changes to these terms", lines: ["We may update these terms. The updated date appears at the top of this page, and continued use of the site or services after an update means you accept the revised terms.", "Terms in a signed contract are not changed by a website update."] },
      { t: "14 · Contact", lines: ["Questions about these terms: info@hillcountryconsultants.com or 470-478-1590.", "Hill Country Consultants — Longview, Texas and Atlanta, Georgia, serving clients nationwide."] },
    ],
  },
  "refund-policy": {
    slug: "refund-policy", nav: "Refund & Cancellation", kicker: "Refund & cancellation",
    title: "Refund & Cancellation Policy", updated: UPDATED,
    intro: "Every scope, rate and term is published on this site and confirmed in writing before you pay. Because of that, all sales are final — and here is the deal both ways: you get every rate, inclusion and limit in writing before you pay, and if we ever fail to deliver, we make it right at no cost to you.",
    sections: [
      { t: "All sales are final", lines: ["We do not issue refunds on plan fees, project payments, class fees, overage charges, or rush charges.", "This applies to every payment, however it was made.", "This no-refund policy is disclosed on this page and again at checkout, where you affirmatively accept it — by checking the acceptance box before payment — every time you book. Your acceptance is recorded with the transaction.", "Nothing here waives a right you cannot waive under applicable Texas or Georgia law; where such a right applies, it controls."] },
      { t: "If we cannot deliver", lines: ["If we fail to deliver an agreed deliverable, we complete it, replace it, or issue an account credit toward future work — at our option and at no additional cost to you.", "Credits do not expire while your account is active.", "This is your remedy in place of a refund."] },
      { t: "Raising an issue", lines: ["If something is not right, contact us first — email info@hillcountryconsultants.com within ten business days of delivery with the reference number from your confirmation.", "We respond within one business day and work the issue against your written scope."] },
      { t: "Why the policy is strict", lines: ["A booking reserves capacity on our schedule and, for standalone work, begins production immediately.", "Rates, inclusions, revision rounds, turnaround and scope limits are published on the relevant service and pricing pages, and the specific scope for your booking is confirmed in writing — in your written scope or quote for scoped work — before payment.", "You have the chance to ask any question, at no cost, in a 30-minute strategy session before you buy."] },
      { t: "Payment disputes", lines: ["Contact us first. If something isn't right, email info@hillcountryconsultants.com or call 470-478-1590 before disputing a charge — we answer within one business day, and first contact is the fastest path to the remedy this policy provides (completion, replacement, or an account credit).", "Your rights. Nothing in this policy removes any right you have under applicable law or your card network's rules, and we do not ask you to waive them.", "How we handle a dispute. Because every scope, rate, inclusion and limit is disclosed and accepted in writing before payment, if a payment dispute is raised on delivered or in-progress work we respond directly to your card issuer with the written scope, your point-of-sale acceptance record, and the delivery record.", "Bad-faith disputes. Where a dispute is raised in bad faith on work delivered as agreed, we reserve our contractual and legal remedies, including recovery of related costs to the extent the law allows. This is a term between the parties and does not limit your ability to raise a dispute with your issuer.", "An account with an open payment dispute may be paused until it is resolved."] },
      { t: "Cancelling a plan", lines: ["Plans run the agreed term and cancel at the end of it, per your contract.", "Cancelling mid-term does not refund fees already paid, and any remaining term obligation in your contract still applies.", "Written notice to info@hillcountryconsultants.com starts the process."] },
      { t: "Classes and events", lines: ["A class or event payment reserves the date, the team and the materials.", "A confirmed class may be rescheduled once, at no charge, with at least fourteen days’ written notice, subject to availability.", "Inside fourteen days, or for a second reschedule, the payment is forfeited.", "No-shows are not refunded or rescheduled."] },
      { t: "Quotes and strategy sessions", lines: ["Quote requests cost nothing and create no obligation.", "The 30-minute strategy session is free and can be cancelled or rescheduled at any time."] },
    ],
  },
  privacy: {
    slug: "privacy", nav: "Privacy Policy", kicker: "Privacy policy",
    title: "Privacy Policy", updated: UPDATED,
    intro: "What we collect, why we collect it, and what we do with it. We do not sell your information.",
    sections: [
      { t: "Information you give us", lines: ["Contact and business details submitted through forms on this site: name, business, email, phone, industry, timeline and what you tell us about your needs.", "How you heard about us, and any referral, employee, or marketing-source code you enter — used to route your inquiry and to credit a referral where one applies.", "Booking details: the services selected, requested start date, deadline and project notes.", "Client materials and credentials provided during onboarding."] },
      { t: "Payment information", lines: ["Electronic payments are processed securely through the Stripe secure payment system, our payment provider. We do not store full payment card numbers or security codes on this site or in our records.", "We keep the transaction reference, amount, date and what was purchased, for accounting and tax records."] },
      { t: "How we use information", lines: ["To respond to inquiries, prepare quotes and proposals, and deliver the services you booked.", "To invoice, keep records, and meet tax and legal obligations.", "To communicate about your engagement, including reviews and reporting at your tier cadence."] },
      { t: "How we share information", lines: ["We do not sell or rent your information.", "We share it only with service providers who help us operate — payment processing, hosting, email, file storage, password management — and with team members and subcontractors bound by confidentiality.", "We disclose information when required by law or to protect our legal rights."] },
      { t: "Client credentials", lines: ["Credentials are collected through a password manager, held with the least access needed to do the work, and never kept in plain text.", "At offboarding, credentials are returned or revoked and access is removed."] },
      { t: "Employment applicants", lines: ["If you apply for a job through our Careers page, we collect the information in the application: your name, contact details and mailing address; the position and availability; work-authorization answers; education and employment history; professional references; skills, certifications and licenses; a portfolio or website and any work-sample links; and any résumé or credential files you upload.", "We also collect equipment and security attestations, your consent to a background check, and a signed certification. Voluntary self-identification (gender, race/ethnicity, veteran and disability status) is exactly that — voluntary, kept separate from the hiring decision, and never used to evaluate your application.", "Applicant information is used only to evaluate your application and to communicate with you about it. It is shared only with the people involved in hiring and, where applicable, a background-check provider — never sold.", "We keep applicant records only as long as needed for the hiring process and any period required by law, and you can ask us to delete information we are not required to keep by emailing info@hillcountryconsultants.com."] },
      { t: "Retention", lines: ["Engagement records, contracts and transaction records are kept as long as needed for the engagement and for the periods required by tax and business law.", "Client work product and assets are returned at offboarding.", "You can ask us to delete inquiry information we are not required to keep."] },
      { t: "Your choices", lines: ["Ask us what we hold about you, ask for a correction, or ask for deletion where the law allows it — email info@hillcountryconsultants.com.", "Ask to stop receiving non-essential email at any time. Service communication about an active engagement continues while the engagement is active."] },
      { t: "Cookies and analytics", lines: ["This site uses only what it needs to function and to remember your progress in a booking.", "We use privacy-friendly, cookieless analytics (Vercel Web Analytics and Speed Insights) to understand which pages are visited and how the site performs. These tools do not use cookies, do not track you across other sites, and do not collect personally identifying information.", "We do not use advertising trackers. If that ever changes, this policy will be updated first."] },
      { t: "Security", lines: ["We use reasonable administrative and technical safeguards, including access limits and a password manager for credentials.", "No method of transmission or storage is perfectly secure, and we cannot guarantee absolute security."] },
      { t: "Business use and age", lines: ["This site and our services are intended for businesses and organizations, and for adults age 18 and over.", "We do not knowingly collect information from children."] },
      { t: "Changes and contact", lines: ["Updates appear here with a new date at the top of the page.", "Questions: info@hillcountryconsultants.com or 470-478-1590."] },
    ],
  },
};

export const LEGAL_ORDER: (keyof typeof LEGAL)[] = ["policies", "terms", "refund-policy", "privacy"];
